const PDFDocument = require('pdfkit');
const Trip = require('../models/Trip');

/**
 * Generates and streams a PDF version of the travel itinerary.
 */
exports.downloadTripPDF = async (req, res, next) => {
    try {
        const trip = await Trip.findById(req.params.id);
        if (!trip) return res.status(404).json({ message: "Trip not found" });

        // Set headers for file download
        res.setHeader('Content-disposition', `attachment; filename=Itinerary_${trip.destination.replace(/\s+/g, '_')}.pdf`);
        res.setHeader('Content-type', 'application/pdf');

        const doc = new PDFDocument({ margin: 50, size: 'A4' });
        doc.pipe(res);

        // --- PDF Design ---
        // Header
        doc.fillColor('#1a365d')
            .fontSize(28)
            .font('Helvetica-Bold')
            .text(`Your Journey to ${trip.destination}`, { align: 'center' });

        doc.moveDown(0.5);
        doc.strokeColor('#cbd5e0')
            .lineWidth(1)
            .moveTo(50, doc.y)
            .lineTo(545, doc.y)
            .stroke();
        doc.moveDown();

        // Trip Summary
        doc.fillColor('#2d3748')
            .fontSize(12)
            .font('Helvetica-Bold')
            .text('Trip Overview', { underline: true });

        doc.font('Helvetica')
            .fontSize(10)
            .text(`Starting Point: ${trip.origin || 'Not specified'}`)
            .text(`Duration: ${trip.days} Days`)
            .text(`Travel Mode: ${trip.mode.toUpperCase()} (${trip.peopleCount} People)`)
            .text(`Interests: ${Array.isArray(trip.interests) ? trip.interests.join(', ') : 'General'}`);

        doc.moveDown();

        // Itinerary Days
        if (trip.itinerary && Array.isArray(trip.itinerary.dailyPlan)) {
            trip.itinerary.dailyPlan.forEach((day, index) => {
                // New page if needed
                if (doc.y > 650) doc.addPage();

                doc.fillColor('#3182ce')
                    .fontSize(16)
                    .font('Helvetica-Bold')
                    .text(`Day ${day.day}: ${day.title}`);

                doc.moveDown(0.5);

                if (Array.isArray(day.activities)) {
                    day.activities.forEach((act, actIndex) => {
                        const activityName = typeof act === 'string' ? act : act.name;
                        const activityAddress = typeof act === 'object' ? act.address : null;

                        doc.fillColor('#2d3748')
                            .fontSize(11)
                            .font('Helvetica-Bold')
                            .text(`${actIndex + 1}. ${activityName}`, { indent: 20 });

                        if (activityAddress) {
                            doc.fillColor('#718096')
                                .fontSize(9)
                                .font('Helvetica-Oblique')
                                .text(`Location: ${activityAddress}`, { indent: 35 });
                        }
                        doc.moveDown(0.3);
                    });
                }

                if (day.weather) {
                    doc.moveDown(0.2)
                        .fillColor('#4a5568')
                        .fontSize(9)
                        .font('Helvetica')
                        .text(`Forecast: ${day.weather}`, { indent: 20 });
                }

                doc.moveDown(1);
            });
        }

        // Footer
        const pageCount = doc.bufferedPageRange().count;
        for (let i = 0; i < pageCount; i++) {
            doc.switchToPage(i);
            doc.fontSize(8)
                .fillColor('#a0aec0')
                .text(
                    `Generated by AI Travel Planner - Page ${i + 1} of ${pageCount}`,
                    50,
                    doc.page.height - 50,
                    { align: 'center' }
                );
        }

        doc.end();
    } catch (err) {
        console.error("PDF Generation Error:", err);
        next(err);
    }
};
